import { createUseStyles } from 'react-jss';
export const useStyles = createUseStyles(
  {
    homePageRoot: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      paddingTop: 100,
      fontSize: 32,
      fontWeight: 700,
      gap: 20,
    },
    createNews: {
      border: '1px solid #D3D3D3',
      outline: 'none',
      width: 'fit-content',
      minWidth: 720,
      padding: 20,
      borderRadius: 8,
      backgroundColor: '#FFFFFF',
      margin: [20, 0],
      transition: 'transform 0.3s, box-shadow 0.3s',
      textAlign: 'center',
    },
    flex: {
      display: 'flex',
      flexDirection: 'row',
    },
    inputLikeContent: {
      width: '100%',
      backgroundColor: '#D3D3D3',
      borderRadius: 20,
      cursor: 'pointer',
      '&:after': {
        content: '"Click here to Add news "',
        fontSize: 16,
        fontWeight: '700',
        display: 'flex',
        color: '#333',
        padding: 10,
        borderRadius: '4px',
        pointerEvents: 'none',
      },
    },
    firstLetter: {
      width: '150px',
      height: '150px',
      backgroundColor: '#ddd',
      border: '4px solid #FFFFFF',
      borderRadius: '50%',
      position: 'absolute',
      bottom: 0,
      left: '50%',
      transform: 'translateX(-50%)',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      fontSize: '36px',
      color: '#555',
      fontWeight: 700,
    },
    newsRoot: {
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      alignItems: 'center',
      textAlign: 'center',
    },
    profileContainer: {
      width: '100%',
      position: 'relative',
      textAlign: 'center',
    },

    profilePic: {
      display: 'flex',
      justifyContent: 'center',
      flexDirection: 'column',
      alignItems: 'center',
    },
  },
  { name: 'page' }
);
